title: Byjoon Cloud
author: Byjoon
url: "https://byjoon-cloud.github.io/moonwork" # GitHub Pages URL로 자동 설정됨
baseurl: ""  # GitHub Pages base URL로 자동 설정됨
description: > # description of the site (multiple lines allowed)
  Byjoon Cloud의 기술 블로그입니다. 클라우드, 개발, 인프라 등 다양한 IT 관련 내용을 다룹니다.

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

twitter:
    username: byjoon_cloud # 트위터 계정이 있다면 수정
    card: summary_large_image

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark" # 다크 모드 유지
  appearance_toggle: true # 테마 전환 버튼 활성화
  back_home_text: "홈으로" # 한글로 변경
  date_format: "%Y-%m-%d" # 날짜 형식 유지
  show_description: true # 사이트 설명 표시
  show_navbar: true # 네비게이션 바 표시
  show_footer: true # 푸터 표시
  show_copyright: true # 저작권 표시
  # following keys are using to create home layout
  show_projects: true # 포트폴리오 표시
  show_blog: true # 블로그 포스트 표시
  show_old_projects: true # 이전 프로젝트 표시
  show_misc_list: false # 기타 목록 표시
  show_reading_time: true # 읽기 시간 표시
  show_tags: true # 태그 표시
  # options for "home" page
  home:
    title_projects: "프로젝트"
    title_misc_list: "상세 정보"
    title_blog: "블로그"
    title_old_projects: "이전 프로젝트"

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
